#!/bin/sh

# This hook will add changed directories to the commit message

COMMIT_MSG_FILE=$1

STAGED_DIRECTORIES=$(git diff --name-only --staged | xargs -L1 dirname | cut -d "/" -f1 | uniq)

STRING="$STAGED_DIRECTORIES\n$(cat $COMMIT_MSG_FILE)"
BASE_DIR=$(basename "`pwd`")

STRING=$(sed 's/\./'"$BASE_DIR"'/g' <<< $STAGED_DIRECTORIES)

echo -e $STRING > $COMMIT_MSG_FILE
